### ISSUE TITLE
Strange problem, `floating-point precision` issue with JS

### ISSUE THREAD

**Issue by nooooocato** [48Club/web3_app#2]
Case: https://bscscan.com/tx/0x966ef15e8e495dfa7b7fd2368e300460e48ddbcb81c0248b8f64d6a7905d854d

![image](https://github.com/48Club/web3_app/assets/11002280/e19f96f4-b3a2-487c-9246-0aed8be0517f)

# "amt":"823181972.0000001"

AMT must be int in protocol

The input data is: 8.23181972

**Comment by du5** [comment]
fix by https://github.com/48Club/web3_app/commit/1b748e7c8e3097458a05b75837892e655b24e5e5
